FROM dockerfile/java:oracle-java8
MAINTAINER bert.godon@gmail.com	
EXPOSE 8081
CMD java -jar bookService-0.0.1-SNAPSHOT.jar
ADD target/bookService-0.0.1-SNAPSHOT.jar /data/bookService-0.0.1-SNAPSHOT.jar