FROM java:openjdk-8u45-jdk
MAINTAINER bert.godon@gmail.com	
EXPOSE 8081
CMD java -jar bookService-0.0.1-SNAPSHOT.jar
ADD build/bookService-0.0.1-SNAPSHOT.jar /data/bookService-0.0.1-SNAPSHOT.jar .